name: Build-Deploy

on:
  push:
    branches:
    - master
      
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: 'Running the integration test'
      run: |
        sh ./build.sh
    - name: Start Jenkins Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://sudheer-gajula-dev01.colo.rubrik.com"
        user: "ubuntu"
        token: 6a8c66f10913a18a11f6e8fa9931fe60
        job: "Jarvis_Metadata_Upload"
